from __future__ import annotations

import argparse
import json
from pathlib import Path

from phase2_authz_runtime import build_matrix_payload, sync_next_canonical_from_source

ROOT = Path(__file__).resolve().parents[2]
OUT_MD = ROOT / "docs" / "specs" / "PHASE2_AUTHZ_MATRIX.md"
OUT_JSON = ROOT / "docs" / "specs" / "PHASE2_AUTHZ_MATRIX.runtime.json"


def _to_md_table(headers: list[str], rows: list[list[str]]) -> str:
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    for row in rows:
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def _bool_label(v: bool) -> str:
    return "yes" if v else "no"


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate Phase 2 authorization matrix from runtime routes")
    parser.add_argument("--sync-next-canonical", action="store_true", help="refresh PHASE2_NEXT_ROUTE_POLICY.json from current source")
    parser.add_argument("--check", action="store_true", help="exit non-zero if gate fails")
    args = parser.parse_args()

    if args.check and args.sync_next_canonical:
        raise SystemExit("--check and --sync-next-canonical cannot be used together")

    if args.sync_next_canonical:
        synced = sync_next_canonical_from_source()
        print(f"Synced canonical entries: {len(synced)}")

    payload = build_matrix_payload()

    fastapi_rows = [
        [
            r["endpoint"],
            r["method"],
            r["policy"],
            ", ".join(r["dependency_names"]),
            r["source"],
        ]
        for r in payload["fastapi"]["routes"]
    ]
    next_rows = [
        [
            r["route"],
            r["method"],
            r["policy"],
            _bool_label(r["auth_header_forward"]),
            _bool_label(r["status_propagation"]),
            _bool_label(r["detail_error_passthrough"]),
            r["source"],
        ]
        for r in payload["next"]["routes"]
    ]

    md = "\n".join(
        [
            "# Phase 2 API Authorization Matrix",
            "",
            "Generated by scripts/security/generate_phase2_authz_matrix.py (runtime extraction).",
            "",
            "## FastAPI Endpoints (Runtime)",
            "",
            _to_md_table(["endpoint", "method", "policy", "dependencies", "source"], fastapi_rows),
            "",
            "## Next API Routes",
            "",
            _to_md_table(
                ["route", "method", "policy", "auth_header_forward", "status_propagation", "detail_error_passthrough", "source"],
                next_rows,
            ),
            "",
            "## Gate Summary",
            "",
            f"- fastapi_unclassified_count: {payload['gate']['fastapi_unclassified_count']}",
            f"- fastapi_duplicate_count: {payload['gate']['fastapi_duplicate_count']}",
            f"- next_unclassified_count: {payload['gate']['next_unclassified_count']}",
            f"- next_failure_count: {payload['gate']['next_failure_count']}",
            f"- pass: {payload['gate']['pass']}",
        ]
    )

    OUT_MD.write_text(md + "\n", encoding="utf-8")
    OUT_JSON.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(f"Wrote: {OUT_MD}")
    print(f"Wrote: {OUT_JSON}")
    print(f"FastAPI routes: {payload['fastapi']['count']}")
    print(f"Next routes: {payload['next']['count']}")
    print(f"Gate pass: {payload['gate']['pass']}")

    if args.check and not payload["gate"]["pass"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
