-- Phase 3M fresh-project bootstrap: service-role-only ML/blob persistence.
-- Browser roles receive neither table grants nor storage-object access.

CREATE TABLE IF NOT EXISTS public.races_ultimate (
    race_id TEXT PRIMARY KEY,
    data JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT races_ultimate_data_object CHECK (jsonb_typeof(data) = 'object')
);

CREATE TABLE IF NOT EXISTS public.race_results_ultimate (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    race_id TEXT NOT NULL REFERENCES public.races_ultimate(race_id) ON DELETE CASCADE,
    horse_number TEXT NOT NULL,
    data JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT race_results_ultimate_race_horse_key UNIQUE (race_id, horse_number),
    CONSTRAINT race_results_ultimate_data_object CHECK (jsonb_typeof(data) = 'object')
);

CREATE TABLE IF NOT EXISTS public.model_metadata (
    model_id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL DEFAULT 'shared',
    storage_path TEXT NOT NULL,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT model_metadata_object
        CHECK (metadata IS NULL OR jsonb_typeof(metadata) = 'object')
);

CREATE TABLE IF NOT EXISTS public.horse_pedigree (
    horse_id TEXT PRIMARY KEY,
    sire TEXT,
    dam TEXT,
    damsire TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.ml_models (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    model_name TEXT NOT NULL,
    model_type TEXT NOT NULL,
    model_data BYTEA,
    accuracy DOUBLE PRECISION,
    precision_score DOUBLE PRECISION,
    recall_score DOUBLE PRECISION,
    f1_score DOUBLE PRECISION,
    feature_importance JSONB,
    training_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    is_active BOOLEAN NOT NULL DEFAULT true
);

CREATE INDEX IF NOT EXISTS idx_race_results_ultimate_race_id
    ON public.race_results_ultimate(race_id);
CREATE INDEX IF NOT EXISTS idx_model_metadata_created_at
    ON public.model_metadata(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ml_models_active
    ON public.ml_models(is_active, training_date DESC);

CREATE OR REPLACE FUNCTION public.phase3m_normalize_ultimate_horse_number()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
BEGIN
    NEW.horse_number := COALESCE(
        NULLIF(btrim(NEW.horse_number), ''),
        NULLIF(btrim(NEW.data ->> 'horse_number'), ''),
        NULLIF(btrim(NEW.data ->> 'horse_num'), '')
    );
    IF NEW.horse_number IS NULL THEN
        RAISE EXCEPTION 'race_results_ultimate horse_number is required'
            USING ERRCODE = '23502';
    END IF;
    RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.phase3m_normalize_ultimate_horse_number()
    FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.phase3m_normalize_ultimate_horse_number()
    TO service_role;

DO $$
DECLARE
    target_table TEXT;
    trigger_name TEXT;
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_catalog.pg_trigger
        WHERE tgname = 'phase3m_race_results_ultimate_horse_number'
          AND tgrelid = 'public.race_results_ultimate'::regclass
          AND NOT tgisinternal
    ) THEN
        EXECUTE 'CREATE TRIGGER phase3m_race_results_ultimate_horse_number BEFORE INSERT OR UPDATE ON public.race_results_ultimate FOR EACH ROW EXECUTE FUNCTION public.phase3m_normalize_ultimate_horse_number()';
    END IF;

    FOREACH target_table IN ARRAY ARRAY[
        'races_ultimate',
        'race_results_ultimate',
        'model_metadata',
        'horse_pedigree'
    ]
    LOOP
        trigger_name := 'phase3m_' || target_table || '_set_updated_at';
        IF NOT EXISTS (
            SELECT 1
            FROM pg_catalog.pg_trigger
            WHERE tgname = trigger_name
              AND tgrelid = format('public.%I', target_table)::regclass
              AND NOT tgisinternal
        ) THEN
            EXECUTE format(
                'CREATE TRIGGER %I BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.phase3m_set_updated_at()',
                trigger_name,
                target_table
            );
        END IF;
    END LOOP;
END;
$$;

ALTER TABLE public.races_ultimate ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.race_results_ultimate ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.model_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.horse_pedigree ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ml_models ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.races_ultimate FORCE ROW LEVEL SECURITY;
ALTER TABLE public.race_results_ultimate FORCE ROW LEVEL SECURITY;
ALTER TABLE public.model_metadata FORCE ROW LEVEL SECURITY;
ALTER TABLE public.horse_pedigree FORCE ROW LEVEL SECURITY;
ALTER TABLE public.ml_models FORCE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE
    public.races_ultimate,
    public.race_results_ultimate,
    public.model_metadata,
    public.horse_pedigree,
    public.ml_models
    FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.race_results_ultimate_id_seq
    FROM PUBLIC, anon, authenticated;
GRANT ALL ON TABLE
    public.races_ultimate,
    public.race_results_ultimate,
    public.model_metadata,
    public.horse_pedigree,
    public.ml_models
    TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.race_results_ultimate_id_seq
    TO service_role;

INSERT INTO storage.buckets (
    id,
    name,
    public,
    file_size_limit,
    allowed_mime_types
)
VALUES (
    'models',
    'models',
    false,
    104857600,
    ARRAY['application/octet-stream', 'application/x-python-serialized-object']::TEXT[]
)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    public = false,
    file_size_limit = EXCLUDED.file_size_limit,
    allowed_mime_types = EXCLUDED.allowed_mime_types;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_catalog.pg_policies
        WHERE schemaname = 'storage'
          AND tablename = 'objects'
          AND policyname = 'phase3m_models_browser_deny'
    ) THEN
        EXECUTE $policy$
            CREATE POLICY phase3m_models_browser_deny
            ON storage.objects
            AS RESTRICTIVE
            FOR ALL
            TO anon, authenticated
            USING (bucket_id <> 'models')
            WITH CHECK (bucket_id <> 'models')
        $policy$;
    END IF;
END;
$$;
